// Mock data for development and fallback when API is unavailable
export const mockPlayers = [
  {
    id: "1",
    name: "Kyle Filipowski",
    number: "30",
    position: "C",
    height: "6'11\"",
    weight: "248 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 17.4,
      reb: 8.1,
      ast: 2.3,
      stl: 1.2,
      blk: 1.4,
      fgPct: 52.3,
      tpPct: 38.9,
      ftPct: 76.5,
      min: 32.1,
      plusMinus: 8.7,
    },
    last5: { pts: 18.2, reb: 7.8, ast: 2.1 },
  },
  {
    id: "2",
    name: "Jeremy Roach",
    number: "3",
    position: "G",
    height: "6'2\"",
    weight: "180 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 14.2,
      reb: 3.1,
      ast: 3.4,
      stl: 1.1,
      blk: 0.3,
      fgPct: 45.8,
      tpPct: 35.2,
      ftPct: 82.1,
      min: 28.5,
      plusMinus: 6.2,
    },
    last5: { pts: 15.8, reb: 2.9, ast: 3.7 },
  },
  {
    id: "3",
    name: "Tyrese Proctor",
    number: "5",
    position: "G",
    height: "6'5\"",
    weight: "190 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 12.8,
      reb: 4.2,
      ast: 4.1,
      stl: 1.3,
      blk: 0.2,
      fgPct: 41.7,
      tpPct: 33.8,
      ftPct: 78.9,
      min: 30.2,
      plusMinus: 5.8,
    },
    last5: { pts: 13.4, reb: 4.5, ast: 4.3 },
  },
  {
    id: "4",
    name: "Mark Mitchell",
    number: "25",
    position: "F",
    height: "6'8\"",
    weight: "220 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 11.6,
      reb: 5.8,
      ast: 1.9,
      stl: 0.8,
      blk: 0.9,
      fgPct: 48.2,
      tpPct: 29.4,
      ftPct: 71.3,
      min: 26.7,
      plusMinus: 4.1,
    },
    last5: { pts: 12.1, reb: 6.2, ast: 2.0 },
  },
  {
    id: "5",
    name: "Dariq Whitehead",
    number: "0",
    position: "F",
    height: "6'7\"",
    weight: "200 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 9.8,
      reb: 3.4,
      ast: 1.7,
      stl: 0.9,
      blk: 0.6,
      fgPct: 44.1,
      tpPct: 36.7,
      ftPct: 69.8,
      min: 22.3,
      plusMinus: 3.2,
    },
    last5: { pts: 10.5, reb: 3.7, ast: 1.9 },
  },
  {
    id: "6",
    name: "Dereck Lively II",
    number: "1",
    position: "C",
    height: "7'1\"",
    weight: "230 lbs",
    photoUrl: null,
    teamLogo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
    perGame: {
      pts: 8.2,
      reb: 6.9,
      ast: 1.1,
      stl: 0.5,
      blk: 2.4,
      fgPct: 56.8,
      tpPct: 0,
      ftPct: 63.4,
      min: 24.8,
      plusMinus: 7.3,
    },
    last5: { pts: 8.8, reb: 7.2, ast: 1.3 },
  },
];

export const mockTeamAverages = {
  pts: 12.3,
  reb: 5.2,
  ast: 2.4,
  stl: 1.0,
  blk: 1.0,
  fgPct: 48.2,
  tpPct: 35.6,
  ftPct: 73.7,
};

export const mockHypeIndex = 78;

// Mock API responses
export const mockApiResponses = {
  leagues: {
    response: [
      { id: 12, name: "NCAA", type: "League", logo: "https://a.espncdn.com/i/teamlogos/leagues/500/ncaa.png" },
      { id: 1, name: "NBA", type: "League", logo: "https://a.espncdn.com/i/teamlogos/leagues/500/nba.png" },
    ]
  },
  teams: {
    response: [
      {
        id: 150,
        name: "Duke",
        code: "DUKE",
        logo: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
        country: { name: "USA" },
        founded: 1905,
        national: false,
      }
    ]
  },
  players: {
    response: mockPlayers.map(player => ({
      id: parseInt(player.id),
      firstname: player.name.split(' ')[0],
      lastname: player.name.split(' ').slice(1).join(' '),
      name: player.name,
      number: parseInt(player.number),
      position: player.position,
      height: player.height,
      weight: player.weight,
      photo: player.photoUrl,
      team: { logo: player.teamLogo }
    }))
  },
  statistics: {
    response: mockPlayers.map(player => ({
      player: { id: parseInt(player.id) },
      games: { played: 25 },
      points: { total: player.perGame.pts * 25 },
      rebounds: { total: player.perGame.reb * 25 },
      assists: { total: player.perGame.ast * 25 },
      steals: { total: player.perGame.stl * 25 },
      blocks: { total: player.perGame.blk * 25 },
      fieldGoals: { percentage: player.perGame.fgPct.toString() },
      threePointers: { percentage: player.perGame.tpPct.toString() },
      freeThrows: { percentage: player.perGame.ftPct.toString() },
      minutes: { total: player.perGame.min * 25 },
      plusMinus: { total: player.perGame.plusMinus * 25 },
    }))
  }
};
